import type { Metadata } from 'next';
import LegalPage from '@/components/legal/LegalPage';

export const metadata: Metadata = {
  title: 'Privacy Policy | PropPilot.ai',
  description: 'Privacy Policy for PropPilot.ai, including how user, content, and Facebook Page data are collected and used.',
};

const sections = [
  {
    title: '1. Information We Collect',
    paragraphs: ['We may collect the following information:'],
    bullets: [
      'Account information such as name, email address, and login information',
      'Property listing information entered by users',
      'Images, videos, captions, and post content uploaded or generated by users',
      'Social media account connection information, such as Facebook Page ID, Page name, access token, and permissions granted by the user',
      'Usage data, such as actions performed in the platform and system logs',
    ],
  },
  {
    title: '2. How We Use Information',
    paragraphs: ['We use the information to:'],
    bullets: [
      'Provide and improve PropPilot.ai services',
      'Allow users to create, preview, schedule, and publish property marketing content',
      'Connect with supported social media platforms such as Facebook Pages',
      'Generate AI-assisted marketing captions, scripts, and post content',
      'Maintain security, prevent abuse, and troubleshoot technical issues',
    ],
  },
  {
    title: '3. Facebook Data Usage',
    paragraphs: [
      'When you connect a Facebook account or Facebook Page, PropPilot.ai may request permissions required to manage and publish content to Pages that you authorize.',
      'We only use Facebook data to:',
    ],
    bullets: [
      'Display the Facebook Pages you manage',
      'Allow you to select a Page for publishing',
      'Publish posts, images, or videos only when you request it',
      'Show post status or related publishing results',
      'We do not sell Facebook data to third parties.',
    ],
  },
  {
    title: '4. Data Sharing',
    paragraphs: ['We do not sell your personal information. We may share limited data only when necessary with:'],
    bullets: [
      'Service providers that help operate our platform',
      'Social media platforms when you choose to publish content',
      'Legal authorities if required by law',
    ],
  },
  {
    title: '5. Data Storage and Security',
    paragraphs: [
      'We use reasonable technical and organizational measures to protect your information. Access tokens and sensitive information should be stored securely and used only for authorized actions.',
    ],
  },
  {
    title: '6. User Control and Data Deletion',
    paragraphs: ['You may disconnect your social media account at any time. You may also request deletion of your account data by contacting us.'],
  },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      description="PropPilot.ai respects your privacy. This Privacy Policy explains how we collect, use, store, and protect information when you use our platform."
      sections={sections}
    />
  );
}
